const joi = require('@hapi/joi');

const formIdSchema = joi.string().regex(/^[0-9]{1,50}$/);

const createFormSchema = {
  nombre_empresa: joi.string(),
  ingreso_mensual: joi.number(),
  cargo_empresa: joi.string(),
  ruc_empresa: joi.string().length(13),
  direccion_empresa: joi.string(),
  identificacion: joi.number(),
  direccion_hogar: joi.string(),
  nombre_conyuge: joi.string(),
  apellido_conyuge: joi.string(),
  ingreso_mensual_conyuge: joi.number(),

  // Before

  categoria: joi.string().max(100),
  cod_tipo_persona_juridica: joi.string().max(100),
  restringir_info: joi.string().max(100),
  cod_persona: joi.string().max(100),
  nombres: joi.string().max(100),
  nombre_1: joi.string().max(100),
  nombre_2: joi.string().max(100),
  apellido_paterno: joi.string().max(100),
  apellido_materno: joi.string().max(100),
  kind_of_person_id: joi.number().required(),
  es_autoretenedor: joi.boolean(),
  cod_pais: joi.string().max(100),
  nombre_correspondencia: joi.string().max(100),
  nombre_usual: joi.string().max(100),
  cod_tipo: joi.string().max(100),
  cod_perfil_operativo: joi.string().max(100),
  cod_tipo_actividad_econ: joi.string().max(100),
  cod_perfil_financiero: joi.string().max(100),
  cod_segmento: joi.string().max(100),
  cod_subtipo_segmento: joi.string().max(100),
  cod_actividad: joi.string().max(100),
  razon_social: joi.string().max(100),
  observacion: joi.string().max(100),
  fecha_nacimiento: joi.date(),
  cod_pais_nacimiento: joi.string().max(100),
  secuencia_nacimiento: joi.string().max(100),
  codigo_nacimiento: joi.string().max(100),
  sexo: joi.string().max(100),
  estado_civil: joi.string().max(100),
  separacion_bien: joi.string().max(100),
  num_cargas: joi.number(),
  tiene_capitulacion_bienes: joi.boolean(),
  tiene_disolucion_soc_conyugal: joi.boolean(),
  apellido_casada: joi.string().max(100),
  cod_profesion: joi.string().max(100),
  cod_tipo_empleo: joi.string().max(100),
  lugar_trabajo: joi.string().max(100),
  direccion_empresa_labora: joi.string().max(100),
  telefono_empresa_labora: joi.string().max(100),
  cod_pais_labora: joi.string().max(100),
  secuencia_labora: joi.string().max(100),
  codigo_labora: joi.string().max(100),
  cargo: joi.string().max(100),
  cod_tipo_activ_econ_labora: joi.string().max(100),
  fecha_ingreso_trabajo: joi.date(),
  sueldo_mensual: joi.number(),
  cod_moneda: joi.string().max(100),
  ingresos_familiares: joi.number(),
  cod_moneda_ing_familiar: joi.string().max(100),
  num_patronal_emp: joi.string().max(100),
  capital_social_emp: joi.string().max(100),
  cod_moneda_capital: joi.string().max(100),
  objeto_emp: joi.string().max(100),
  escritura: joi.string().max(100),
  fecha_constitucion_emp: joi.date(),
  fecha_registro: joi.date(),
  numero_empleados: joi.number(),
  numero_sucursales: joi.number(),
  fecha_nomina_accionistas: joi.date(),
  fecha_vencimiento_cia: joi.date(),
  registro_inscripcion: joi.string().max(100),
  cod_persona_notario: joi.string().max(100),
  fecha_certif_oblig: joi.date(),
  ingresado_por: joi.string().max(100),
  fecha_ingreso: joi.date(),
  modificado_por: joi.string().max(100),
  fecha_modificacion: joi.date(),
  lista_negra: joi.string().max(100),
  lista_negra_des: joi.string().max(100),
  politicamente_expuesto: joi.string().max(100),
  cod_estado_persona: joi.string().max(100),
  origen_fondos: joi.string().max(100),
  modificable: joi.string().max(100),
  cod_tipo_forma_pago: joi.string().max(100),
  num_cuenta_cliente: joi.string().max(100),
  cod_tipo_cuenta_cliente: joi.string().max(100),
  cod_entidad_cta_cliente: joi.string().max(100),
  cod_tipo_entidad_cta_cliente: joi.string().max(100),
  cod_moneda_fpago: joi.string().max(100),
  observaciones: joi.string().max(100),
  exonerado_imp: joi.string().max(100),
  tipo_ingreso_patrimonio_partic: joi.string().max(100),
  patrimonio_particular: joi.string().max(100),
  status: joi.string().max(10),
};

// const updateFormJuridicoSchema = {
//     name: joi.string().max(100),
//     current_amount: joi.number(),
//     status: joi.string().max(10)
// };

module.exports = {
  formIdSchema,
  createFormSchema,
  // updateFormJuridicoSchema,
};
